config/routes.rb
Rails.application.routes.draw do
  resources :powers
  resources :planets
  resources :aliens
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/alien.rb
class Alien < ApplicationRecord
	belongs_to :planet

	has_many :alien_powers
	has_many :power, through: :alien_powers

	validates_presence_of :name
end

app/models/alien_power.rb
class AlienPower < ApplicationRecord
  belongs_to :alien
  belongs_to :power
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/planet.rb
class Planet < ApplicationRecord
end

app/models/power.rb
class Power < ApplicationRecord

	has_many :alien_powers
	has_many :aliens, through: :alien_powers
end

app/controllers/aliens_controller.rb
class AliensController < ApplicationController
  before_action :set_alien, only: [:show, :edit, :update, :destroy]

  # GET /aliens
  # GET /aliens.json
  def index
    @aliens = Alien.all
  end

  # GET /aliens/1
  # GET /aliens/1.json
  def show
  end

  # GET /aliens/new
  def new
    @alien = Alien.new
  end

  # GET /aliens/1/edit
  def edit
  end

  # POST /aliens
  # POST /aliens.json
  def create
    @alien = Alien.new(alien_params)

    respond_to do |format|
      if @alien.save
        format.html { redirect_to @alien, notice: 'Alien was successfully created.' }
        format.json { render :show, status: :created, location: @alien }
      else
        format.html { render :new }
        format.json { render json: @alien.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /aliens/1
  # PATCH/PUT /aliens/1.json
  def update
    respond_to do |format|
      if @alien.update(alien_params)
        format.html { redirect_to @alien, notice: 'Alien was successfully updated.' }
        format.json { render :show, status: :ok, location: @alien }
      else
        format.html { render :edit }
        format.json { render json: @alien.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /aliens/1
  # DELETE /aliens/1.json
  def destroy
    @alien.destroy
    respond_to do |format|
      format.html { redirect_to aliens_url, notice: 'Alien was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_alien
      @alien = Alien.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def alien_params
      params.require(:alien).permit(:name, :age, :planet_id, :power_ids => [])
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/planets_controller.rb
class PlanetsController < ApplicationController
  before_action :set_planet, only: [:show, :edit, :update, :destroy]

  # GET /planets
  # GET /planets.json
  def index
    @planets = Planet.all
  end

  # GET /planets/1
  # GET /planets/1.json
  def show
  end

  # GET /planets/new
  def new
    @planet = Planet.new
  end

  # GET /planets/1/edit
  def edit
  end

  # POST /planets
  # POST /planets.json
  def create
    @planet = Planet.new(planet_params)

    respond_to do |format|
      if @planet.save
        format.html { redirect_to @planet, notice: 'Planet was successfully created.' }
        format.json { render :show, status: :created, location: @planet }
      else
        format.html { render :new }
        format.json { render json: @planet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /planets/1
  # PATCH/PUT /planets/1.json
  def update
    respond_to do |format|
      if @planet.update(planet_params)
        format.html { redirect_to @planet, notice: 'Planet was successfully updated.' }
        format.json { render :show, status: :ok, location: @planet }
      else
        format.html { render :edit }
        format.json { render json: @planet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /planets/1
  # DELETE /planets/1.json
  def destroy
    @planet.destroy
    respond_to do |format|
      format.html { redirect_to planets_url, notice: 'Planet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_planet
      @planet = Planet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def planet_params
      params.require(:planet).permit(:name)
    end
end

app/controllers/powers_controller.rb
class PowersController < ApplicationController
  before_action :set_power, only: [:show, :edit, :update, :destroy]

  # GET /powers
  # GET /powers.json
  def index
    @powers = Power.all
  end

  # GET /powers/1
  # GET /powers/1.json
  def show
  end

  # GET /powers/new
  def new
    @power = Power.new
  end

  # GET /powers/1/edit
  def edit
  end

  # POST /powers
  # POST /powers.json
  def create
    @power = Power.new(power_params)

    respond_to do |format|
      if @power.save
        format.html { redirect_to @power, notice: 'Power was successfully created.' }
        format.json { render :show, status: :created, location: @power }
      else
        format.html { render :new }
        format.json { render json: @power.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /powers/1
  # PATCH/PUT /powers/1.json
  def update
    respond_to do |format|
      if @power.update(power_params)
        format.html { redirect_to @power, notice: 'Power was successfully updated.' }
        format.json { render :show, status: :ok, location: @power }
      else
        format.html { render :edit }
        format.json { render json: @power.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /powers/1
  # DELETE /powers/1.json
  def destroy
    @power.destroy
    respond_to do |format|
      format.html { redirect_to powers_url, notice: 'Power was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_power
      @power = Power.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def power_params
      params.require(:power).permit(:name)
    end
end

app/helpers/aliens_helper.rb
module AliensHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/planets_helper.rb
module PlanetsHelper
end

app/helpers/powers_helper.rb
module PowersHelper
end

app/views/aliens/_form.html.erb
<%= form_for(alien) do |f| %>
  <% if alien.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(alien.errors.count, "error") %> prohibited this alien from being saved:</h2>

      <ul>
      <% alien.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :planet %>
    <%= collection_select(:alien, :planet_id, Planet.all, :id, :name) %>
  </div>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :age %>
    <%= f.number_field :age %>
  </div>

  <div class="field">
    <%= f.label :powers %>
    <%= collection_check_boxes(:alien, :power_ids, Power.all, :id, :name) %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/aliens/edit.html.erb
<h1>Editing Alien</h1>

<%= render 'form', alien: @alien %>

<%= link_to 'Show', @alien %> |
<%= link_to 'Back', aliens_path %>

app/views/aliens/index.html.erb
<h1>Listing aliens</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Planet</th>
      <th>Age</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @aliens.each do |alien| %>
      <tr>
        <td><%= alien.name %></td>
        <td><%= alien.planet %></td>
        <td><%= alien.age %></td>
        <td><%= link_to 'Show', alien %></td>
        <td><%= link_to 'Edit', edit_alien_path(alien) %></td>
        <td><%= link_to 'Destroy', alien, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Alien', new_alien_path %>

app/views/aliens/new.html.erb
<h1>New Alien</h1>

<%= render 'form', alien: @alien %>

<%= link_to 'Back', aliens_path %>

app/views/aliens/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @alien.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @alien.age %>
</p>

<%= link_to 'Edit', edit_alien_path(@alien) %> |
<%= link_to 'Back', aliens_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Spacerails</title>
    <%= csrf_meta_tags %>

   
  </head>

  <body>
  <div id="menu">
  	<%= link_to "ALIENS", aliens_path %>
  	<%= link_to "PLANETS", planets_path %>
  	<%= link_to "POWERS", powers_path %>
  </div>
    <%= yield %>
  </body>
</html>

app/views/planets/_form.html.erb
<%= form_for(planet) do |f| %>
  <% if planet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(planet.errors.count, "error") %> prohibited this planet from being saved:</h2>

      <ul>
      <% planet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/planets/edit.html.erb
<h1>Editing Planet</h1>

<%= render 'form', planet: @planet %>

<%= link_to 'Show', @planet %> |
<%= link_to 'Back', planets_path %>

app/views/planets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Planets</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @planets.each do |planet| %>
      <tr>
        <td><%= planet.name %></td>
        <td><%= link_to 'Show', planet %></td>
        <td><%= link_to 'Edit', edit_planet_path(planet) %></td>
        <td><%= link_to 'Destroy', planet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Planet', new_planet_path %>

app/views/planets/new.html.erb
<h1>New Planet</h1>

<%= render 'form', planet: @planet %>

<%= link_to 'Back', planets_path %>

app/views/planets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @planet.name %>
</p>

<%= link_to 'Edit', edit_planet_path(@planet) %> |
<%= link_to 'Back', planets_path %>

app/views/powers/_form.html.erb
<%= form_for(power) do |f| %>
  <% if power.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(power.errors.count, "error") %> prohibited this power from being saved:</h2>

      <ul>
      <% power.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/powers/edit.html.erb
<h1>Editing Power</h1>

<%= render 'form', power: @power %>

<%= link_to 'Show', @power %> |
<%= link_to 'Back', powers_path %>

app/views/powers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Powers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @powers.each do |power| %>
      <tr>
        <td><%= power.name %></td>
        <td><%= link_to 'Show', power %></td>
        <td><%= link_to 'Edit', edit_power_path(power) %></td>
        <td><%= link_to 'Destroy', power, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Power', new_power_path %>

app/views/powers/new.html.erb
<h1>New Power</h1>

<%= render 'form', power: @power %>

<%= link_to 'Back', powers_path %>

app/views/powers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @power.name %>
</p>

<%= link_to 'Edit', edit_power_path(@power) %> |
<%= link_to 'Back', powers_path %>